import Image from "next/image";
import Link from "next/link";
import { ArrowUpLeft, FolderTree, ImageIcon, Layers3, Package } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import type { AdminCategory } from "../../types";
import { AdminPageHeader } from "../ui/admin-page-header";
import { CategoryCreateDialog } from "./category-create-dialog";

const accents=["bg-cyan-50 text-cyan-700","bg-amber-50 text-amber-700","bg-violet-50 text-violet-700","bg-rose-50 text-rose-700"];
export function CategoryList({ categories }: { categories: AdminCategory[] }) {
  return <><AdminPageHeader eyebrow="تنظيم الكتالوج" title="الفئات" description="رتّب أقسام المتجر وافتح أي فئة لإدارة صورتها وفئاتها الفرعية." action={<CategoryCreateDialog order={categories.length+1}/>}/>{categories.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{categories.map((category,index)=><Link href={`/admin/categories/${category.id}`} key={category.id} className="group"><Card className="h-full overflow-hidden border-slate-200/80 py-0 transition-all hover:-translate-y-1 hover:border-cyan-200 hover:shadow-xl hover:shadow-cyan-950/5"><div className="relative h-40 overflow-hidden bg-slate-100">{category.imageUrl?<Image src={category.imageUrl} alt={category.nameAr} fill className="object-cover transition-transform duration-500 group-hover:scale-105" sizes="420px"/>:<div className={`grid size-full place-items-center ${accents[index%accents.length]}`}><ImageIcon className="size-10 opacity-55"/></div>}<Badge variant={category.isActive?"default":"secondary"} className="absolute right-3 top-3 bg-white/90 text-slate-700 backdrop-blur">{category.isActive?"مفعّلة":"مخفية"}</Badge></div><CardContent className="p-5"><div className="mb-4 flex items-start justify-between gap-4"><div><h2 className="text-lg font-black text-slate-900">{category.nameAr}</h2><p className="mt-1 text-[10px] text-slate-400" dir="ltr">/{category.slug}</p></div><span className="grid size-9 place-items-center rounded-xl bg-cyan-50 text-cyan-700 transition group-hover:bg-cyan-700 group-hover:text-white"><ArrowUpLeft className="size-4"/></span></div><div className="grid grid-cols-2 gap-2"><span className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><Layers3 className="size-4 text-violet-500"/><b>{category.subcategories.length}</b> فرعية</span><span className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><Package className="size-4 text-cyan-600"/><b>{category.productCount}</b> منتج</span></div></CardContent></Card></Link>)}</div>:<Card className="border-dashed py-16 text-center"><CardContent><FolderTree className="mx-auto mb-4 size-12 text-cyan-200"/><h2 className="font-black">ابدأ بأول فئة</h2><p className="mt-2 text-sm text-slate-500">ستظهر الفئات هنا كبطاقات منظمة وسهلة الوصول.</p></CardContent></Card>}</>;
}
