"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import type { Product, ProductSize } from "@/domains/catalog/types";
import { adminRequest } from "../api";
import type { AdminCategory } from "../types";

type DraftSize=ProductSize&{isNew?:boolean};
type ProductEditorResult={action:"created"|"updated"|"deleted";productId:number};
export function useProductEditor(product:Product|undefined,categories:AdminCategory[],onComplete:(result:ProductEditorResult)=>void){const router=useRouter();const[busy,setBusy]=useState(false);const[categoryId,setCategoryId]=useState(String(product?.categoryId??categories[0]?.id??""));const[subcategoryId,setSubcategoryId]=useState(String(product?.subcategoryId??""));const[sizes,setSizes]=useState<DraftSize[]>(product?.sizes.length?product.sizes:[{id:-1,label:"الحصة",price:0,caloriesLabel:"",isNew:true}]);
  const category=categories.find(item=>String(item.id)===categoryId);const availableSubcategories=category?.subcategories??[];
  function updateSize(id:number,patch:Partial<DraftSize>){setSizes(current=>current.map(item=>item.id===id?{...item,...patch}:item))}function addSize(){setSizes(current=>[...current,{id:-Date.now(),label:"",price:0,caloriesLabel:"",isNew:true}])}
  async function removeSize(size:DraftSize){if(sizes.length===1){toast.error("يجب أن يبقى حجم واحد على الأقل");return}if(size.id>0){try{await adminRequest(`/sizes/${size.id}`,{method:"DELETE"})}catch(error){toast.error(error instanceof Error?error.message:"تعذّر حذف الحجم");return}}setSizes(current=>current.filter(item=>item.id!==size.id))}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{const common={nameAr:form.get("nameAr"),nameEn:form.get("nameEn"),category:category?.nameAr??"غير مصنف",categoryId:Number(categoryId)||null,subcategoryId:Number(subcategoryId)||null,emoji:form.get("emoji"),description:form.get("description"),isActive:form.get("isActive")==="on",isFeatured:form.get("isFeatured")==="on",isNew:form.get("isNew")==="on",sortOrder:Number(form.get("sortOrder")??999)};let productId=product?.id;if(productId){await adminRequest(`/products/${productId}`,{method:"PATCH",body:JSON.stringify(common)});for(const size of sizes){if(size.id>0)await adminRequest(`/sizes/${size.id}`,{method:"PATCH",body:JSON.stringify({label:size.label,price:size.price,caloriesLabel:size.caloriesLabel,sortOrder:0})});else await adminRequest(`/products/${productId}/sizes`,{method:"POST",body:JSON.stringify({label:size.label,price:size.price,caloriesLabel:size.caloriesLabel,sortOrder:99})})}}else{const[first,...rest]=sizes;const created=await adminRequest<{id:number}>("/products",{method:"POST",body:JSON.stringify({...common,size:{label:first.label,price:first.price,caloriesLabel:first.caloriesLabel,sortOrder:1}})});productId=created.id;for(const size of rest)await adminRequest(`/products/${productId}/sizes`,{method:"POST",body:JSON.stringify({label:size.label,price:size.price,caloriesLabel:size.caloriesLabel,sortOrder:99})})}const file=form.get("image");if(file instanceof File&&file.size&&productId){const upload=new FormData();upload.set("file",file);await adminRequest(`/products/${productId}/image`,{method:"POST",body:upload})}toast.success(product?"تم تحديث المنتج":"تم إنشاء المنتج");router.refresh();onComplete({action:product?"updated":"created",productId})}catch(error){toast.error(error instanceof Error?error.message:"تعذّر حفظ المنتج")}finally{setBusy(false)}}
  async function deleteProduct(){if(!product||!confirm(`حذف ${product.nameAr} نهائياً؟`))return;setBusy(true);try{await adminRequest(`/products/${product.id}`,{method:"DELETE"});toast.success("تم حذف المنتج");router.refresh();onComplete({action:"deleted",productId:product.id})}catch(error){toast.error(error instanceof Error?error.message:"تعذّر حذف المنتج")}finally{setBusy(false)}}
  return{busy,categoryId,setCategoryId,subcategoryId,setSubcategoryId,availableSubcategories,sizes,updateSize,addSize,removeSize,submit,deleteProduct}}
