"use client";

import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import { Bold, Heading2, Italic, List, ListOrdered, Quote, Redo2, Undo2 } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";

function initialHtml(value:string){if(!value)return "<p></p>";if(/<\/?[a-z][\s\S]*>/i.test(value))return value;return `<p>${value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll("\n","<br>")}</p>`}
export function RichTextEditor({name,defaultValue=""}:{name:string;defaultValue?:string}){const[html,setHtml]=useState(()=>initialHtml(defaultValue));const editor=useEditor({extensions:[StarterKit.configure({heading:{levels:[2,3]}})],content:html,immediatelyRender:false,onUpdate:({editor})=>setHtml(editor.getHTML())});const actions=[{label:"عريض",icon:Bold,active:"bold",run:()=>editor?.chain().focus().toggleBold().run()},{label:"مائل",icon:Italic,active:"italic",run:()=>editor?.chain().focus().toggleItalic().run()},{label:"عنوان",icon:Heading2,active:"heading",run:()=>editor?.chain().focus().toggleHeading({level:2}).run()},{label:"قائمة",icon:List,active:"bulletList",run:()=>editor?.chain().focus().toggleBulletList().run()},{label:"قائمة رقمية",icon:ListOrdered,active:"orderedList",run:()=>editor?.chain().focus().toggleOrderedList().run()},{label:"اقتباس",icon:Quote,active:"blockquote",run:()=>editor?.chain().focus().toggleBlockquote().run()}];return <div className="overflow-hidden rounded-2xl border border-blue-100 bg-white"><div className="flex flex-wrap gap-1 border-b border-blue-100 bg-blue-50/70 p-2">{actions.map(action=><Button key={action.label} type="button" variant={editor?.isActive(action.active)?"default":"ghost"} size="icon-sm" title={action.label} className={editor?.isActive(action.active)?"bg-blue-600 text-white hover:bg-blue-700":"text-slate-600"} onClick={action.run}><action.icon/><span className="sr-only">{action.label}</span></Button>)}<span className="mx-1 w-px bg-blue-100"/><Button type="button" variant="ghost" size="icon-sm" title="تراجع" onClick={()=>editor?.chain().focus().undo().run()}><Undo2/><span className="sr-only">تراجع</span></Button><Button type="button" variant="ghost" size="icon-sm" title="إعادة" onClick={()=>editor?.chain().focus().redo().run()}><Redo2/><span className="sr-only">إعادة</span></Button></div><EditorContent editor={editor} className="[&_.ProseMirror]:min-h-56 [&_.ProseMirror]:p-4 [&_.ProseMirror]:leading-8 [&_.ProseMirror]:outline-none [&_.ProseMirror_h2]:my-3 [&_.ProseMirror_h2]:text-xl [&_.ProseMirror_h2]:font-black [&_.ProseMirror_h3]:my-2 [&_.ProseMirror_h3]:text-lg [&_.ProseMirror_h3]:font-bold [&_.ProseMirror_ul]:list-disc [&_.ProseMirror_ul]:pr-6 [&_.ProseMirror_ol]:list-decimal [&_.ProseMirror_ol]:pr-6 [&_.ProseMirror_blockquote]:my-3 [&_.ProseMirror_blockquote]:border-r-4 [&_.ProseMirror_blockquote]:border-blue-300 [&_.ProseMirror_blockquote]:bg-blue-50 [&_.ProseMirror_blockquote]:p-3"/><input type="hidden" name={name} value={html}/></div>}
