import type { Product } from "./types";

export const seedProducts: Product[] = [
  { id: 1, nameAr: "ورق عنب", nameEn: "Waraq Enab", category: "مطبوخ", emoji: "🍃", description: "ورق عنب أصيل محشوّ بأرز بلدي متبّل بعناية، يُلفّ بإحكام ويُطهى على نار هادئة حتى يكتسب قوامه الطري ونكهته الحامضة الغنية — طبق بيتي دافئ يليق بأي سفرة.", imageUrl: "/products/1.webp", isFeatured: true, isNew: false, sizes: [{ id: 1, label: "20 حبة", price: 45, caloriesLabel: "900–1300 سعرة" }, { id: 2, label: "40 حبة", price: 85, caloriesLabel: "1800–2600 سعرة" }] },
  { id: 2, nameAr: "ملفوف", nameEn: "Malfouf", category: "مطبوخ", emoji: "🥬", description: "لفائف ملفوف طازجة محشوّة بمزيج متوازن من الأرز واللحم والتوابل المنزلية، تُطهى بصبر حتى تذوب في الفم — طعم بيتي أصيل بلمسة تغميسة المميزة.", imageUrl: "/products/2.webp", isFeatured: true, isNew: false, sizes: [{ id: 3, label: "20 حبة", price: 45, caloriesLabel: "700–900 سعرة" }, { id: 4, label: "40 حبة", price: 85, caloriesLabel: "1400–1800 سعرة" }] },
  { id: 3, nameAr: "جريش", nameEn: "Jaresh", category: "مطبوخ", emoji: "🫕", description: "جريش سعودي أصيل، حبّاته مطحونة طحناً خشناً ومطبوخة مع اللحم والتوابل ببطء حتى تصل لقوامها الكريمي الغني — دفء المطبخ السعودي في كل ملعقة.", imageUrl: "/products/3.webp", isFeatured: true, isNew: false, sizes: [{ id: 5, label: "صغير", price: 35, caloriesLabel: "300–500 سعرة" }, { id: 6, label: "وسط", price: 80, caloriesLabel: "700–950 سعرة" }, { id: 7, label: "كبير", price: 120, caloriesLabel: "1000–1400 سعرة" }] },
  { id: 4, nameAr: "فتة مكرونة وورق عنب", nameEn: "Pasta & Waraq Enab Fatta", category: "مطبوخ", emoji: "🍝", description: "دمج مبتكر بين المكرونة الذهبية وورق العنب المحشوّ، مغطى بصوص لبني كريمي ولمسة دبس رمان حامضة ومكسرات محمّصة — تجربة فتة مختلفة في كل قضمة.", imageUrl: "/products/4.webp", isFeatured: true, isNew: false, sizes: [{ id: 8, label: "الحصة", price: 45, caloriesLabel: "950–1400 سعرة" }] },
  { id: 5, nameAr: "فتة ورق عنب", nameEn: "Fattet Waraq Enab", category: "مطبوخ", emoji: "🥗", description: "فتة غنية تجمع طبقات من الخبز المحمّص وورق العنب المحشوّ، تُتوَّج بلبن كريمي وصوص دبس رمان وحبات رمان طازجة ومكسرات مقرمشة — طبق احتفالي بنكهات متوازنة بين الحامض والدسم.", imageUrl: "/products/5.webp", isFeatured: true, isNew: true, sizes: [{ id: 9, label: "الحصة", price: 45, caloriesLabel: "800–1200 سعرة" }] },
  { id: 6, nameAr: "مسخن", nameEn: "Musakhan", category: "مطبوخ", emoji: "🫔", description: "لفائف مسخن بخبز طازج محشوّ بدجاج متبّل بالسماق والبصل المحمّر وزيت الزيتون البلدي، تُلفّ وتُخبز حتى تكتسب قرمشة خفيفة من الخارج وطراوة شهية من الداخل — نكهة شرقية أصيلة بأسلوب تغميسة.", imageUrl: "/products/6.webp", isFeatured: true, isNew: true, sizes: [{ id: 10, label: "25 حبة", price: 67, caloriesLabel: "1500–2250 سعرة" }] },
  { id: 7, nameAr: "آيس كريم كراميل", nameEn: "Caramel Ice Cream", category: "حلويات", emoji: "🍮", description: "آيس كريم منزلي بقوام حريري ناعم، محضّر بكراميل غني مطبوخ ببطء وطبقة علوية لامعة من صوص الكراميل — حلى بارد يُختتم به أي وجبة بحلاوة متوازنة.", imageUrl: "/products/7.webp", isFeatured: true, isNew: false, sizes: [{ id: 11, label: "صغير", price: 70, caloriesLabel: "700–1100 سعرة" }, { id: 12, label: "كبير", price: 120, caloriesLabel: "1200–1700 سعرة" }] },
  { id: 8, nameAr: "محبوج", nameEn: "Mahbouj", category: "غموس", emoji: "🌶️", description: "غموس محبوج ناري بمزيج من الفلفل والتوابل السعودية المميزة، يُحضّر طازجاً ليضيف نكهة قوية وحارة لأي طبق أو سفرة — لعشاق النكهات الجريئة.", imageUrl: "/products/8.webp", isFeatured: true, isNew: false, sizes: [{ id: 13, label: "البرطمان", price: 35, caloriesLabel: "500–850 سعرة" }, { id: 14, label: "برطمانان", price: 64, caloriesLabel: "1000–1700 سعرة" }] },
  { id: 9, nameAr: "تعتيمة", nameEn: "Tatema", category: "غموس", emoji: "🫙", description: "غموس تعتيمة الكريمي بقوام ناعم متجانس ونكهة متوازنة بين الحموضة الخفيفة والدسم، مثالي مع الخبز الطازج أو كطبق جانبي يكمل أي وجبة.", imageUrl: "/products/9.webp", isFeatured: true, isNew: false, sizes: [{ id: 15, label: "البرطمان", price: 40, caloriesLabel: "600–950 سعرة" }, { id: 16, label: "برطمانان", price: 74, caloriesLabel: "1200–1900 سعرة" }] },
  { id: 10, nameAr: "صوص دبس رمان", nameEn: "Pomegranate Molasses Sauce", category: "صوصات", emoji: "🍷", description: "صوص دبس الرمان الطبيعي، حلو حامض بقوام مركّز، يضيف لمسة لامعة ونكهة متوازنة لأطباقك المفضلة أو للتزيين النهائي.", imageUrl: null, isFeatured: false, isNew: false, sizes: [{ id: 17, label: "الحصة", price: 3, caloriesLabel: "25–40 سعرة" }, { id: 18, label: "5 حصص", price: 12, caloriesLabel: "125–200 سعرة" }] },
  { id: 11, nameAr: "صوص تعتيمة", nameEn: "Tatema Sauce", category: "صوصات", emoji: "🥛", description: "صوص تعتيمة الكريمي، رفيق مثالي يكمّل النكهة ويضيف قوامًا غنيًا لأي طبق تُقدّمه معه.", imageUrl: null, isFeatured: false, isNew: false, sizes: [{ id: 19, label: "الحصة", price: 3, caloriesLabel: "80–140 سعرة" }, { id: 20, label: "5 حصص", price: 12, caloriesLabel: "400–700 سعرة" }] },
];
